# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_monitor_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='datetime_event_start',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='event_title',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='seatgeek_event_id',
        ),
    ]
