# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventprice',
            options={'get_latest_by': 'id'},
        ),
        migrations.AlterField(
            model_name='eventprice',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='event.Event'),
        ),
    ]
