# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20170410_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
