# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20170426_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='datetime_start_local',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
