# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170201_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
