# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
