# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime_event_start', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('event_title', models.CharField(max_length=255)),
                ('seatgeek_event_id', models.CharField(max_length=10)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
