# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='email',
        ),
        migrations.AddField(
            model_name='monitor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitor',
            name='datetime_event_start',
            field=models.DateTimeField(),
        ),
    ]
