# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170201_0541'),
        ('alert', '0002_auto_20170121_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='event.Event'),
        ),
    ]
