# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_monitor_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='external_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
