MONITOR_STATUS_CREATED = 0
MONITOR_STATUS_ACTIVATED = 1
MONITOR_STATUS_DEACTIVATED = 2

MONITOR_STATUSES = {
    MONITOR_STATUS_CREATED: 'Created',
    MONITOR_STATUS_ACTIVATED: 'Activated',
    MONITOR_STATUS_DEACTIVATED: 'Deactivated'
}
